name: Run Python Daily

on:
  schedule:
    - cron: "30 17 * * *"  # Runs every day at 1:25 AM IST
  workflow_dispatch:       # Lets you run manually

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requests
      run: pip install requests        

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run the Python script
      run: python DivineMuhurt_Combined.py

    - name: Commit generated script files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.html
        git commit -m "Add generated script file"
        git push
      continue-on-error: true
      
